export const CITIES_HAS_ERRORED = "CITIES_HAS_ERRORED";
export const CITIES_IS_LOADING = "CITIES_IS_LOADING";
export const CITIES_FETCH_DATA_SUCCESS = "CITIES_FETCH_DATA_SUCCESS";
export const ADD_CITY = "ADD_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const EDIT_CITY = "EDIT_CITY";
